In [81]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import r2_score

In [67]:
data = pd.read_csv("HousePricePrediction.csv")
data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [87]:
data.isnull().sum()
data = data.dropna(subset=['SalePrice'])

In [69]:
X = data.drop(columns = ["SalePrice"])
Y = data["SalePrice"]

In [72]:
X

        Id  MSSubClass  LotArea  OverallCond  YearRemodAdd  TotalBsmtSF
0        0          60     8450            5          2003        856.0
1        1          20     9600            8          1976       1262.0
2        2          60    11250            5          2002        920.0
3        3          70     9550            5          1970        756.0
4        4          60    14260            5          2000       1145.0
...    ...         ...      ...          ...           ...          ...
1455  1455          60     7917            5          2000        953.0
1456  1456          20    13175            6          1988       1542.0
1457  1457          70     9042            9          2006       1152.0
1458  1458          20     9717            6          1996       1078.0
1459  1459          20     9937            6          1965       1256.0

[1460 rows x 6 columns]

In [52]:
X_train , X_test , Y_train, Y_test = train_test_split(
    X,Y, test_size = 0.2, random_state = 42
)

In [53]:
X_test.head()

        Id  MSSubClass  LotArea  OverallCond  YearRemodAdd  TotalBsmtSF
2437  2437          85     6760            5          1962        896.0
2470  2470          60     9780            9          2005        976.0
2359  2359          20     6285            5          1977        894.0
789    789          60    12205            8          2007        832.0
1642  1642          60     7500            5          2001       1058.0

Id              0
MSSubClass      0
MSZoning        4
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     1
BsmtFinSF2      1
TotalBsmtSF     1
SalePrice       0
dtype: int64

In [74]:
X_train.isnull().sum()

Id              0
MSSubClass      0
LotArea         0
OverallCond     0
YearRemodAdd    0
TotalBsmtSF     0
dtype: int64

In [73]:
X_train['TotalBsmtSF'] = X_train['TotalBsmtSF'].fillna(X_train['TotalBsmtSF'].mean())

In [75]:
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [76]:
Y_predict = model.predict(X_test)

In [79]:
Y_predict

array([158122.45570373, 192684.5081095 , 165592.24225927, 188387.99527239,
       189426.37037479, 217845.3635929 , 139770.79729698, 201952.29730407,
       148441.83637482, 203020.9897465 , 181149.8881778 , 199562.03322583,
       166152.27939869, 194275.86800931, 170762.73759705, 182370.33598561,
       159703.0698776 , 186677.05490448, 143114.40571082, 172940.28699612,
       194905.77487611, 139589.65310793, 135224.36458856, 194582.93573582,
       213749.15324237, 187793.52483833, 198161.30504893, 144746.52186845,
       199129.84756775, 164114.02567063, 225488.14596208, 163324.14375835,
       192520.55719675, 190064.69591431, 209745.90881262, 208220.07491435,
       175057.66759104, 179986.09623556, 155716.85148759, 186224.85658881,
       142001.6257425 , 187349.07342519, 219209.46886843, 195400.95818104,
       182724.93350889, 171120.24027332, 202385.38980085, 180333.17105542,
       169992.55509775, 244513.83574186, 165433.8269534 , 179214.08031833,
       141247.50028759, 203835.78457848, 161390.60785234, 136493.6170749 ,
       151337.73390408, 180210.49992041, 214895.51142119, 164274.87156101,
       162854.88819811, 150271.49406842, 177202.77066849, 158815.60173712,
       170438.34583582, 201937.79708895, 201863.17157199, 170123.23019423,
       195053.50633742, 186052.44189057, 189013.90706447, 160643.34208332,
       185038.92949259, 220575.94658632, 134370.16938689, 114276.54760958,
       195663.96230411, 141340.44962315, 199937.64494649, 184152.32451394,
       178068.76712143, 195129.1348413 , 186651.03767417, 150115.18873223,
       177227.86821348, 182334.26339266, 118564.20945909, 176231.18203553,
       142005.62050206, 170982.33388639, 171530.63771371, 136640.70622584,
       158663.53786959, 220241.11557891, 176234.37784319, 167012.21973979,
       164289.07089157, 197278.19525856, 168086.51776988, 174059.29384325,
       183567.78255391, 175935.18477653, 167042.99952153, 216108.07427132,
       191123.73339067, 163212.70686895, 156075.62650111, 168877.15132375,
       218611.30150988, 179576.5281946 , 191493.23163951, 147772.95424585,
       206114.65975685, 247083.82561984, 208626.08801035, 160523.49400109,
       173534.01751664, 204866.98539054, 245571.25508077, 205768.08974141,
       157284.37138639, 172211.81079022, 200361.75811904, 154507.68029485,
       151993.78908248, 156110.60057574, 169814.98624486, 184639.63798416,
       206433.95488602, 209492.31289933, 171421.42398772, 141318.2080436 ,
       199014.7962183 , 171606.24176407, 158294.26116513, 177322.29105489,
       202879.24470532, 197078.65712751, 225874.2137763 , 198931.11333373,
       178760.6356505 , 170264.72728794, 155398.12720776, 189345.61052247,
       219736.93211055, 216636.35451156, 172883.72616874, 237816.32592284,
       188052.51146212, 193962.85137073, 175527.17843936, 219550.60889101,
       139921.21667414, 171683.97386679, 126422.49934432, 140551.6908281 ,
       200456.93543993, 210114.49427981, 163731.19200943, 125564.34601792,
       225907.70255998, 228813.79176985, 210934.56646205, 172145.49430836,
       153694.44280824, 168058.76110111, 225352.16480899, 194817.7702838 ,
       170399.37922255, 137973.98463583, 174171.87000485, 152663.83981328,
       188899.09437944, 199181.8585745 , 194509.75374651, 210520.4373947 ,
       167171.10607921, 181259.00369809, 163628.65570323, 197380.64617583,
       212379.39044596, 203014.79461763, 170484.17886685, 194427.28700925,
       203683.71726515, 198415.14302339, 209715.0010741 , 219864.7761833 ,
       190950.3380478 , 162836.67921709, 203185.98310943, 209550.64666712,
       137111.85701564, 161626.37211982, 186061.15682917, 217617.23973064,
       218199.56163427, 183044.83158852, 253777.20375907, 188068.73731183,
       178196.02590495, 181001.23299314, 164381.75549699, 155789.55014645,
       172977.43830046, 108392.3864501 , 145914.20698058, 189241.19946068,
       151008.73811318, 171213.65053233, 138805.61728917, 166530.25999925,
       212180.69913207, 191062.72327448, 196786.32743683, 144883.50702735,
       195930.32652255, 131400.82721874, 182531.77770453, 176874.95166006,
       132637.23574418, 166532.97510028, 204207.09304939, 114692.51247072,
       217157.0677335 , 174967.12886228, 194747.49456434, 196120.50350384,
       145198.41219363, 129263.10802228, 143724.37396464, 161255.47694635,
       156931.24917927, 184581.89582103, 156496.25883177, 167557.87045156,
       171731.50958122, 181803.20717314, 144504.24701718, 144705.09138416,
       216449.62216294, 180326.26115552, 216730.114687  , 217096.38382395,
       234432.65047481, 194225.83074017, 177555.61095462, 193929.29367958,
       196966.45341998, 178085.80324152, 198325.85543173, 158063.86783277,
       165637.06859519, 151121.17679485, 227864.55411132, 140471.7212457 ,
       165444.780957  , 159514.45274095, 209210.46246026, 182959.08236459,
       153715.69907024, 175720.58629471, 158066.02589983, 215587.36007743,
       228152.76050588, 196818.28146833, 180791.48631444, 197171.61906574,
       217794.36183229, 190077.50658311, 180601.5449265 , 149963.20193265,
       173824.67199669, 133230.1838244 , 208838.85882536, 195602.69223853,
       163268.01637463, 218634.23257256, 175192.92782467, 179416.25406473,
       219935.89812343, 180150.34997668, 163436.35215022, 148958.26767453,
       220926.95673252, 164955.01032855, 194367.88647079, 158812.78420818,
       182954.25863496, 147523.28074306, 186199.38913984, 194245.24398417,
       180874.16629001, 197057.27474864, 182478.95054231, 194067.33070835,
       235750.56623548, 166601.27813612, 166261.71265468, 186187.04002714,
       185706.5605183 , 210048.47975948, 176849.84011899, 205520.2507469 ,
       162881.85328628, 230759.05463108, 184129.12466436, 213722.28021196,
       166155.62277515, 183580.60846176, 182345.06564113, 160951.71918964,
       176279.31409332, 188954.72197347, 156083.10859591, 175730.7184561 ,
       141563.20127371, 162117.34271824, 205893.7319164 , 176765.65367079,
       176734.26029268, 198478.07770547, 210897.04373469, 111383.05883866,
       180690.31993158, 210546.70400873, 183991.55078962, 202606.12497302,
       116358.10216219, 180938.98392057, 146664.09641007, 200921.77016454,
       129268.79527214, 129752.40062609, 209219.46543949, 162046.54629232,
       217920.93791109, 181435.45375824, 174540.72968495, 173561.3483558 ,
       144583.91291413, 175326.85377397, 168608.91650676, 173879.71525047,
       182084.32610676, 170926.73053264, 200771.55945024, 147138.5000786 ,
       181067.33166224, 138731.02013912, 180002.15218849, 198764.68223023,
       161293.24070322, 201731.44262012, 197234.6422067 , 180469.72173637,
       144617.0981182 , 184575.99967573, 164132.14580843, 223351.7844406 ,
       162800.01437093, 194780.36742769, 165625.10676744, 199027.98699633,
       190796.42530842, 190125.6978629 , 200861.91742027, 194705.30274899,
       190458.28719115, 185812.17227556, 161913.07190235, 149593.26323439,
       162222.89771228, 156781.13598481, 181648.74114313, 186476.27345684,
       178768.7805419 , 172829.47455669, 185879.34489087, 166184.46603258,
       173598.84647975, 237639.19158395, 186322.56497171, 188810.29145342,
       143466.00171689, 195910.71513081, 198852.3012578 , 160005.97237016,
       169534.90888262, 165851.29270543, 164175.6700131 , 199454.61870132,
       195521.14524411, 195183.66478844, 185170.86144413, 156211.24209491,
       190785.53310189, 221651.40352072, 166819.80023783, 173911.2775913 ,
       168152.48860915, 114209.37173672, 181302.48533251, 174287.50386384,
       165708.18742281, 211880.72948433, 158411.5715853 , 188033.12066559,
       184586.2167788 , 138321.04786733, 139576.58955015, 168859.679568  ,
       167116.97687552, 202389.50231025, 142463.00277642, 176450.69832962,
       179927.57857507, 181354.54581127, 217296.41946517, 226602.62241544,
       191905.92980757, 153798.7449665 , 177424.05061613, 196414.53533833,
       186655.10281541, 198351.96379858, 223488.38308727, 225778.64709525,
       177528.6598763 , 189749.41762388, 171409.43287936, 144107.64531028,
       165005.47641654, 201828.30373881, 172016.06313486, 180421.40462643,
       145024.43896493, 198818.3333694 , 161086.83841921, 141895.42880367,
       194715.49321669, 147107.91510111, 159921.88778242, 223797.93688185,
       184597.487569  , 149775.25065046, 142077.45540695, 201917.56365631,
       179366.64018689, 170677.68852379, 215575.56191029, 173392.2264405 ,
       186983.3404255 , 184749.951862  , 172820.14033053, 157297.93938507,
       171763.39415776, 158702.16997667, 174216.29068347, 141477.97789902,
       171280.82551666, 187775.85530844, 179994.45027219, 233708.82530193,
       206194.01957518, 149048.44650969, 170644.66512401, 274698.85557616,
       188751.80346368, 147871.79972514, 252400.3125823 , 152577.55700719,
       194724.147255  , 202703.35051781, 195492.64556421, 191141.78805384,
       174775.56748582, 222294.00345131, 186849.2916077 , 148843.68452719,
       222673.48701265, 192705.73785666, 152500.27277054, 216195.60245243,
       176947.14710995, 149921.69567747, 162743.29634145, 176118.75921798,
       156696.98198092, 190153.1149904 , 209578.2237647 , 191638.68487851,
       207851.72175913, 196926.0042254 , 436031.1864658 , 215839.50266872,
       192089.02462663, 207895.45712376, 161436.78875911, 174194.62905103,
       146338.3140492 , 205760.47709475, 190909.14006486, 222793.29249251,
       144150.61917597, 183318.41153454, 140360.33406823, 194401.73133355,
       151811.49996186, 149973.39683368, 199490.54592625, 198859.51425415,
       180745.97670025, 177133.02968318, 204853.55245903, 191341.11353529,
       170796.85554189, 212214.34652982, 165385.29999555, 210326.4260777 ,
       147489.47747703, 171111.56983817, 178644.14291122, 194515.84971625,
       145319.10892322, 168516.20288305, 220427.09496399, 184840.86260008,
       187563.07250284, 159638.70154161, 132745.14784726, 167767.11068426,
       253054.36803278, 201802.99478382, 198103.17751453, 172070.96915954,
       138662.03175568, 159677.5998836 , 212451.38840856, 198197.43652201,
       171252.48531528, 177876.69160284, 177564.14233961, 182698.24560296,
       162604.79926394, 149333.74538589, 179963.69562829, 167829.59443034,
       151187.24092366, 233972.83805925, 201222.38473025, 198752.78293097,
       158432.27751357, 184177.49013742, 229493.02391858, 120486.18422313,
       171989.56135198, 186604.58515918, 158885.49469399, 178122.09019453,
       203786.02549587, 185039.45885771, 180133.05284084, 180609.36830546,
       157801.07406242, 184550.80659806, 133274.11744409, 155371.55682108,
       168759.72884973, 118125.18023913, 198251.5550084 , 201491.54859264,
       146367.69869501, 185482.53717049, 191177.34894747, 166208.39969717,
       178699.81186482, 191795.02412754, 201008.82610836, 163521.71979664,
       225774.06837849, 234967.47948193, 115291.11561851, 210909.46084629])

In [80]:
Y_test

2437    180921.19589
2470    180921.19589
2359    180921.19589
789     187500.00000
1642    180921.19589
            ...
2880    180921.19589
2295    180921.19589
2222    180921.19589
1090     92900.00000
542     213250.00000
Name: SalePrice, Length: 584, dtype: float64

In [84]:
r2 = r2_score(Y_test,Y_predict)
r2

0.2987866985127383